/*
* AppSettings
*
* Generated By LaravelConnect for iOS on 2018-03-16 19:23:24
* 
* Server Code Version: e8c4cad (2018-03-16 14:03:08)
*
*/

import Foundation
import CoreData
import LaravelConnect





protocol AppSettings : LaravelSettings {

}

public extension AppSettings {
    
    var apiKeyHeaderName: String { return "x-connect-api-key" }

    var coreDataModelName: String { return "laravel_connect" }

}
