/*
* AppSettings
*
* Generated By LaravelConnect for iOS on 2018-06-01 21:15:37
* 
* Server Code Version: 2bb6390 2018-06-01 22:06:45
*
*/

import Foundation
import CoreData
import LaravelConnect





public protocol AppSettings : LaravelSettings {

}

public extension AppSettings {
    
    var apiKeyHeaderName: String { return "x-connect-api-key" }

    var coreDataModelName: String { return "laravel_connect" }

    var apiRootPathSegments: [String]  { return ["square1","connect","v1"] }

    var serverVersion: String { return "2bb6390 2018-06-01 22:06:45" }

    var appName: String { return "App\\LaravelConnectDemo" }
}
