/*
* AppSettings
*
* Generated By LaravelConnect for iOS on 2018-06-01 19:20:16
* 
* Server Code Version: 17152ea 2018-06-01 20:06:31
*
*/

import Foundation
import CoreData
import LaravelConnect





public protocol AppSettings : LaravelSettings {

}

public extension AppSettings {
    
    var apiKeyHeaderName: String { return "x-connect-api-key" }

    var coreDataModelName: String { return "laravel_connect" }

    var apiRootPathSegments: [String]  { return ["square1","connect","v1"] }

    var serverVersion: String { return "17152ea 2018-06-01 20:06:31" }

    var appName: String { return "App\\LaravelConnectDemo" }
}
