/*
 * Country
 *
 * Generated By LaravelConnect for iOS on 2018-01-07 21:16:57
 *
 */
 
import Foundation
import CoreData



@objc(Country)
public class Country: NSManagedObject, Decodable {

    enum CodingKeys: String, CodingKey  {
        case id = "id"
case name = "name"
case code = "code"
case createdAt = "created_at"
case updatedAt = "updated_at"
case continentId = "continent_id"
    }

    class var modelPath: String {       
        return "country"
    }
    
    class var primaryKey: String {       
        return "id"
    }

    required convenience public init(from decoder: Decoder) throws {
        // Create NSEntityDescription with NSManagedObjectContext
        guard let contextUserInfoKey = CodingUserInfoKey.context,
            let managedObjectContext = decoder.userInfo[contextUserInfoKey] as? NSManagedObjectContext,
            let entity = NSEntityDescription.entity(forEntityName: "Country", in: managedObjectContext) else {
                fatalError("Failed to decode Country!")
        }
        self.init(entity: entity, insertInto: nil)
        
        // Decode
        
        
    }

}


extension Country {

@NSManaged  public var id: Int64
@NSManaged  public var name: String
@NSManaged  public var code: String
@NSManaged  public var createdAt: NSDate
@NSManaged  public var updatedAt: NSDate
@NSManaged  public var continentId: Int64
 

@NSManaged  public var cities: NSSet
@NSManaged  public var continent: Continent
 

// MARK: Generated accessors for cities
@objc(addCitiesObject:)
@NSManaged  public func addToCities(_ value: City)

@objc(removeCitiesObject:)
 @NSManaged  public func removeFromCities(_ value: City)

@objc(addCities:)
@NSManaged  public func addToCities(_ values: NSSet)

@objc(removeCities:)
@NSManaged  public func removeFromCities(_ values: NSSet)

  

    @nonobjc  public class func fetchRequest() -> NSFetchRequest<Country> {
        return NSFetchRequest<Country>(entityName: "Country")
    }

}
