/*
 * Language
 *
 * Generated By LaravelConnect for iOS on 2018-03-19 15:53:32
 * 
 * Server Code Version: e1ab799 2018-03-19 15:03:07
 *
 */
 
import Foundation
import CoreData
import LaravelConnect




@objc(Language)
public class Language: ConnectModel {


    
    public var relCountries: ConnectManyRelation<Country>!
 

    
    override public func setupRelations() {
        self.relCountries = self.setupRelation(name:"countries")

 
    }


}


extension Language {

    
     

    @NSManaged  public var id: Int64
@NSManaged  public var name: String
@NSManaged  public var createdAt: NSDate
@NSManaged  public var updatedAt: NSDate
 


}


