/*
 * User
 *
 * Generated By LaravelConnect for iOS on 2018-06-01 19:20:16
 * 
 * Server Code Version: 17152ea 2018-06-01 20:06:31
 *
 */
 
import Foundation
import CoreData
import LaravelConnect




@objc(User)
public class User: ConnectModel {


    
    public var relPhone: ConnectOneRelation<Phone>!
public var relCity: ConnectOneRelation<City>!
public var relFriends: ConnectManyRelation<User>!
 

    
    override public func setupRelations() {
        self.relPhone = self.setupRelation(name:"phone")

self.relCity = self.setupRelation(name:"city")

self.relFriends = self.setupRelation(name:"friends")

 
    }


}


extension User {

    
    public typealias Gender = String
 

    @NSManaged  public var id: Int64
@NSManaged  public var name: String
@NSManaged  public var email: String
@NSManaged  public var gender: Gender
@NSManaged  public var createdAt: NSDate
@NSManaged  public var updatedAt: NSDate
@NSManaged  public var cityId: Int64
@NSManaged  public var avatar: UploadedImage
@NSManaged  public var dateOfBirth: NSDate
 


}

extension  User.Gender {
    
            public static let MALE:User.Gender = "male"
            public static let FEMALE:User.Gender = "female"
            public static let UNKNOWN:User.Gender = "unknown"
    
}

